
#数据库连接配置
spring:
  redis:
    host: 127.0.0.1
  session:
    #    指定session的存储类型为redis
    store-type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security_demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: logicDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#      meta-object-handler: com.junjie.common.config.mybatis.TimeMetaObjectHandler

#      metaObjectHandler

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
org:
  junjie:
    oauth2:
      storeType: redis #使用redis 存储token
      jwtSigningKey: junjie
      clients:
        - clientId: test
          clientSecret: test
          accessTokenValiditySeconds: 3600
        - clientId: clientapp
          clientSecret: 112233
          accessTokenValiditySeconds: 3600
