#server:
#  port: 9001
#spring:
#  application:
#    name: service-product
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    username: root
#    password: 123456
#  jpa:
#    database: MySQL
#    show-sql: true
#    open-in-view: true
##配置eureka注册中心地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/
#  instance:
#    #    向注册中心注册服务ID，这里的服务ID写成当前服务的IP和端口号
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    lease-renewal-interval-in-seconds: 5  #默认心跳时间是30，为了方便测试，这里改成5
#    lease-expiration-duration-in-seconds: 15 #续约到期时间，多长时间没有心跳，剔除该服务(默认是90 )
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: logicDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#      meta-object-handler: com.junjie.common.config.mybatis.TimeMetaObjectHandler

#      metaObjectHandler