server:
  port: 9001
  tomcat:
    max-threads: 200

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 8
      max-active: 64
      max-wait: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      keep-alive: true
      phy-max-use-count: 100000
      filter:
        stat:
          connection-stack-trace-enable: true
          slow-sql-millis: 1000
          log-slow-sql: true
          merge-sql: true
        #        # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
        #        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        slf4j:
          enabled: true
          #          statement-create-after-log-enabled: false
          #          statement-close-after-log-enabled: false
          #          result-set-open-after-log-enabled: false
          #          result-set-close-after-log-enabled: false
          statement-log-enabled: true
      time-between-log-stats-millis: 300000
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
#配置eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/
  instance:
    #    向注册中心注册服务ID，这里的服务ID写成当前服务的IP和端口号
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 5  #默认心跳时间是30，为了方便测试，这里改成5
    lease-expiration-duration-in-seconds: 15 #续约到期时间，多长时间没有心跳，剔除该服务(默认是90 )
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

##打印sql 执行日志
#logging:
#  level:
#    com:
#      junjie:
#        product:
#          dao: trace
